In [1]:
import pandas as pd

In [14]:
citi2018_06 = pd.read_csv("Citibike_data/cb-2018-06.csv.zip")
citi2018_07 = pd.read_csv("Citibike_data/cb-2018-07.csv.zip")
citi2018_08 = pd.read_csv("Citibike_data/cb-2018-08.csv.zip")
citi2018_09 = pd.read_csv("Citibike_data/cb-2018-09.csv.zip")
citi2018_10 = pd.read_csv("Citibike_data/cb-2018-10.csv.zip")
citi2018_11 = pd.read_csv("Citibike_data/cb-2018-11.csv.zip")
citi2018_12 = pd.read_csv("Citibike_data/cb-2018-12.csv.zip")
citi2019_01 = pd.read_csv("Citibike_data/cb-2019-01.csv.zip")
citi2019_02 = pd.read_csv("Citibike_data/cb-2019-02.csv.zip")
citi2019_03 = pd.read_csv("Citibike_data/cb-2019-03.csv.zip")
citi2019_04 = pd.read_csv("Citibike_data/cb-2019-04.csv.zip")
citi2019_05 = pd.read_csv("Citibike_data/cb-2019-05.csv.zip")
citi2019_06 = pd.read_csv("Citibike_data/cb-2019-06.csv.zip")
citi2019_06

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,316,2019-06-01 00:05:55.7210,2019-06-01 00:11:11.9940,3187,Warren St,40.721124,-74.038051,3199,Newport Pkwy,40.728745,-74.032108,29677,Subscriber,1993,1
1,280,2019-06-01 00:08:09.0920,2019-06-01 00:12:50.0730,3185,City Hall,40.717733,-74.043845,3267,Morris Canal,40.712419,-74.038526,29571,Subscriber,1984,1
2,2162,2019-06-01 00:13:11.8800,2019-06-01 00:49:14.3640,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,26208,Customer,1969,0
3,2184,2019-06-01 00:13:30.1110,2019-06-01 00:49:54.2250,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,29487,Customer,1969,0
4,139,2019-06-01 00:13:31.8520,2019-06-01 00:15:51.7880,3207,Oakland Ave,40.737604,-74.052478,3207,Oakland Ave,40.737604,-74.052478,29592,Subscriber,1994,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39425,639,2019-06-30 23:38:29.5450,2019-06-30 23:49:09.2110,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,29197,Customer,1986,1
39426,643,2019-06-30 23:38:34.9100,2019-06-30 23:49:17.9690,3677,Glenwood Ave,40.727551,-74.071061,3191,Union St,40.718211,-74.083639,26262,Customer,1990,2
39427,418,2019-06-30 23:42:30.9400,2019-06-30 23:49:29.5360,3679,Bergen Ave,40.722104,-74.071455,3191,Union St,40.718211,-74.083639,29241,Subscriber,1979,1
39428,2529,2019-06-30 23:46:17.5700,2019-07-01 00:28:27.1710,3185,City Hall,40.717733,-74.043845,3213,Van Vorst Park,40.718489,-74.047727,26254,Subscriber,1982,1
39429,831,2019-06-30 23:49:01.6830,2019-07-01 00:02:53.1150,3210,Pershing Field,40.742677,-74.051789,3186,Grove St PATH,40.719586,-74.043117,29551,Subscriber,1988,1